# Generated by Django 4.0.3 on 2022-05-02 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('fechaSolicitud', models.DateField()),
                ('estado', models.CharField(default='solicitud', max_length=50)),
                ('fechaValidacion', models.DateField(null=True)),
                ('acta', models.CharField(max_length=100, null=True)),
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre1', models.CharField(max_length=100)),
                ('nombre2', models.CharField(max_length=100, null=True)),
                ('apellido1', models.CharField(max_length=100)),
                ('apellido2', models.CharField(max_length=100, null=True)),
                ('fechaNacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=1)),
                ('provincia', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('estadoCivil', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('celular', models.IntegerField()),
                ('lugarTrabajo', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('telefonoLugarTrabajo', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conabom.user')),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField()),
                ('nombre1', models.CharField(max_length=100)),
                ('nombre2', models.CharField(max_length=100, null=True)),
                ('apellido1', models.CharField(max_length=100)),
                ('apellido2', models.CharField(max_length=100, null=True)),
                ('parentezco', models.CharField(max_length=50)),
                ('porcentaje', models.IntegerField()),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conabom.socio')),
            ],
        ),
    ]
