# Generated by Django 4.0.3 on 2022-05-28 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conabom', '0005_alter_socio_fechasolicitud_alter_socio_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics/%y/%m/%d')),
                ('title', models.CharField(max_length=150)),
                ('sub_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='socio',
            name='fechaSolicitud',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 11, 28, 48, 864138)),
        ),
    ]
