# Generated by Django 4.0.3 on 2022-05-28 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conabom', '0006_slider_alter_socio_fechasolicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='static/IMG/images/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='fechaSolicitud',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 12, 30, 59, 655560)),
        ),
    ]
