# Generated by Django 4.0.3 on 2022-06-18 21:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conabom', '0008_alter_socio_fechasolicitud_alter_socio_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='afiliado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='fechaSolicitud',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 18, 17, 1, 42, 618751)),
        ),
    ]
