# Generated by Django 4.0.3 on 2022-06-18 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conabom', '0009_alter_beneficiario_afiliado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='telefono',
            field=models.IntegerField(default=8099999999),
        ),
        migrations.AlterField(
            model_name='socio',
            name='fechaSolicitud',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 18, 18, 58, 56, 803028)),
        ),
    ]
