# Generated by Django 4.0.3 on 2022-06-19 02:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conabom', '0010_beneficiario_telefono_alter_socio_fechasolicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='aporte',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socio',
            name='institucionAtencionEmergencia',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='ubicacion',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='fechaSolicitud',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 18, 22, 49, 29, 949749)),
        ),
    ]
