# Generated by Django 4.0.3 on 2022-06-19 07:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conabom', '0011_socio_aporte_socio_institucionatencionemergencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='fechaSolicitud',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 19, 7, 47, 15, 767498)),
        ),
        migrations.AlterField(
            model_name='socio',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
