# Generated by Django 4.0.3 on 2022-06-19 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conabom', '0012_alter_socio_fechasolicitud_alter_socio_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='fechaSolicitud',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 19, 7, 49, 38, 51325)),
        ),
    ]
