# Generated by Django 4.0.3 on 2022-06-19 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conabom', '0013_alter_socio_fechasolicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='fechaSolicitud',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 19, 7, 52, 33, 974369)),
        ),
    ]
