# Generated by Django 4.0.3 on 2022-06-19 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conabom', '0014_alter_socio_fechasolicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='apellido2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='celular',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='fechaSolicitud',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 19, 8, 14, 40, 69160)),
        ),
        migrations.AlterField(
            model_name='socio',
            name='nombre2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
