# Generated by Django 4.0.3 on 2022-06-19 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conabom', '0015_alter_socio_apellido2_alter_socio_celular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='fechaSolicitud',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
