# Generated by Django 4.0.3 on 2022-06-26 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conabom', '0020_alter_socio_acta_alter_socio_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='conabom/pages/static/IMG/images/noticias/%y/%m/%d')),
                ('titulo', models.CharField(blank=True, default='titulo', max_length=300)),
                ('contenido', models.CharField(blank=True, default='detalles', max_length=5000)),
                ('fechaPublicacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='conabom/pages/static/IMG/images/noticias/%y/%m/%d')),
                ('titulo', models.CharField(blank=True, default='titulo', max_length=300)),
                ('contenido', models.CharField(blank=True, default='detalles', max_length=5000)),
                ('fechaPublicacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='socio',
            name='estado',
            field=models.CharField(choices=[('en proceso', 'en proceso'), ('aprobada', 'aprobada'), ('rechazada', 'rechazada')], default='en proceso', max_length=50),
        ),
    ]
