# Generated by Django 4.0.3 on 2022-06-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conabom', '0021_evento_noticia_alter_socio_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
