# Generated by Django 4.0.3 on 2022-06-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conabom', '0022_alter_evento_foto_alter_noticia_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='contenido',
            field=models.TextField(blank=True, default='detalles'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='contenido',
            field=models.TextField(blank=True, default='detalles'),
        ),
    ]
