# Generated by Django 4.0.3 on 2022-06-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conabom', '0023_alter_evento_contenido_alter_noticia_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/%y%m%d'),
        ),
    ]
