# Generated by Django 4.0.3 on 2022-06-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conabom', '0024_alter_evento_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/%y%m%d'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%y%m%d'),
        ),
    ]
