# Generated by Django 4.0.3 on 2022-07-10 12:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conabom', '0025_alter_noticia_foto_alter_slider_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenesGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='galeria/%y%m%d')),
                ('titulo', models.CharField(blank=True, default='titulo', max_length=300)),
                ('fechaPublicacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
