# Generated by Django 4.0.3 on 2022-07-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conabom', '0027_alter_beneficiario_cedula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='banco',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='numeroCuenta',
            field=models.BigIntegerField(null=True),
        ),
    ]
